DROP DATABASE IF EXISTS fantasydb;
CREATE DATABASE fantasydb;

USE fantasydb;

CREATE TABLE NBA_players(
playerId INTEGER AUTO_INCREMENT NOT NULL,
name VARCHAR (50), 
FG INTEGER(10),
PPG INTEGER (10),
RPG INTEGER(10),
APG INTEGER(10),
PRIMARY KEY (playerId)
);

SELECT * FROM NBA_players;

USE fantasydb;

CREATE TABLE Users (
userId INTEGER AUTO_INCREMENT NOT NULL, 
username VARCHAR (10) NOT NULL, 
age INTEGER (10) NOT NULL,
PRIMARY KEY (userId)
);

CREATE TABLE users_players(
id INTEGER AUTO_INCREMENT NOT NULL,
fkPlayerId INTEGER NOT NULL,
fkUserId INTEGER NOT NULL, 
FOREIGN KEY (fkPlayerId) REFERENCES nba_players(playerId)
   ON DELETE CASCADE,
FOREIGN KEY (fkUserId) REFERENCES Users(userId)
   ON DELETE CASCADE,
   PRIMARY KEY(id)
);